export enum AchievementEventType {
  DEVICE_PAIRED = 'DEVICE_PAIRED',
  PLANT_ADDED = 'PLANT_ADDED',
  PLANT_CHANGED = 'PLANT_CHANGED',
  SENSOR_READING_RECEIVED = 'SENSOR_READING_RECEIVED',
  PROFILE_PICTURE_CHANGED = 'PROFILE_PICTURE_CHANGED',
}

